import turtle
kochop = turtle.Turtle()
def borgo():
  kochop.forward(100)
  kochop.right(90)
  kochop.forward(100)
  kochop.right(90)
  kochop.forward(100)
  kochop.right(90)
  kochop.forward(100)
borgo()  
kochop.forward(100)
borgo()
kochop.forward(100)
borgo()
kochop.forward(100)
borgo()